server:
  port: 2040
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: nishanneupane
    
  jpa:
    hibernate:
      ddl-auto: update
     
    show-sql: true
    
    
      
    